### ISSUE TITLE
broke project

### ISSUE THREAD

**Issue by hakanngul** [alexop-a/Demo-Cuke-To-ReportPortal-Importer#1]
it wasn't run to demo.reportportal or something and local report portal could you check your projecT?

**Comment by alexop-a** [comment]
Did you updated the **rp-cucumber-import.properties** file with correct properties?
You need to set the **rp.importer.reportPortal.XXX** to valid ones.
I just set those locally and run it:
```
rp.importer.reportPortal.projectName=default_personal
rp.importer.reportPortal.apiKey=demo-cuke-rp-importer_rFrb_XfIRlGpHadObr4d99nBtKCz85A0_r6S5Q9GgL6h3eAwYiK2_f0C5-iq8jQ-
rp.importer.reportPortal.endpoint=https://demo.reportportal.io
```
and the data were imported:
- https://demo.reportportal.io/ui/#default_personal/launches/all/14
- https://demo.reportportal.io/ui/#default_personal/launches/all/15

Note, that you need to use java17 when running that.
